print('Information about the types of formats')
anything = input('Type a variable: ')
print('The type is: ', type(anything))
print('{} is blank? ' .format(anything), anything.isspace())
print('{} is numeric? '.format(anything), anything.isnumeric())
print('{} is alphabetic? ' .format(anything), anything.isalpha())
print('{} is alphanumeric? '.format(anything), anything.isalnum())
print('{} is uppercase? '.format(anything), anything.isupper())
print('{} is lowcase? '.format(anything), anything.islower())
